NORMALIZE_COUNTRY_NAME = {
    **{ k: "Albania"                    for k in ["flag of albania (1939–1943).svg"] },
    **{ k: "Australia"                  for k in ["Australia", "AUS"] },
    **{ k: "Belgium"                    for k in ["Belgium"] },
    **{ k: "Brazil"                     for k in ["Vargas Era"] },
    **{ k: "Britain"                    for k in ["Britain", "UK", "United Kingdom", "raf roundel.svg", "ensign of the royal air force.svg"] },
    **{ k: "British India"              for k in ["British India"] },
    **{ k: "Bulgaria"                   for k in ["Kingdom of Bulgaria"] },
    **{ k: "Canada"                     for k in ["Canada", "Flag of Canada (1921–1957).svg"] },
    **{ k: "China"                      for k in ["Republic of China (1912-49)", "Republic of China (1912–1949)", "Republic of China (1912-1949)"] },
    **{ k: "Croatia"                    for k in ["Independent State of Croatia"] },
    **{ k: "Czechoslovakia"             for k in ["Czechoslovakia"] },
    **{ k: "Danzig"                     for k in ["Free City of Danzig"] },
    **{ k: "Denmark"                    for k in ["Denmark", "Kingdom of Denmark", "Royal Standard of Denmark.svg",
                                                  "Flag of Denmark (state).svg"] },
    **{ k: "Empire of Japan"            for k in ["Empire of Japan", "Japan"] },
    **{ k: "Finland"                    for k in ["Finland"] },
    **{ k: "France"                     for k in ["FRA-3", "France", "Free France", "Free French", "French Third Republic"] },
    **{ k: "Germany"                    for k in ["Nazi Germany", "War Ensign of Germany (1938–1945).svg", "Germany", "Flag of Germany (1935–1945).svg",
                                                  "Flag Schutzstaffel.svg"] },
    **{ k: "Greece"                     for k in ["Greece", "Kingdom of Greece"] },
    **{ k: "Hungary"                    for k in ["Kingdom of Hungary (1920–46)", "Kingdom of Hungary (1920–1946)"] },
    **{ k: "Luxembourg"                 for k in ["Luxembourg", "LUX"] },
    **{ k: "Malayan Union"              for k in ["Malayan Union"] },
    **{ k: "New Zealand"                for k in ["Dominion of New Zealand", "New Zealand"] },
    **{ k: "Netherlands"                for k in ["Netherlands"] },
    **{ k: "Norway"                     for k in ["Flag of Norway, state with proportions.svg", "Norway", "NOR", "Flag of Norway, state.svg", 
                                                  "Flag of Norway, state with proportions.svg"] },
    **{ k: "Iceland"                    for k in ["Kingdom of Iceland"] },
    **{ k: "Italy"                      for k in ["Fascist Italy", "Fascist Italy (1922-1943)", "Fascist Italy (1922–1943)", "Kingdom of Italy",
                                                  "Italian Social Republic"] },
    **{ k: "Italian Partisans"          for k in ["Flag of Italian Committee of National Liberation.svg"] },
    **{ k: "Iran"                       for k in ["Iran", "Pahlavi Iran"] },
    **{ k: "Iraq"                       for k in ["Iraq"] },
    **{ k: "Palestine"                  for k in ["Palestinian flag 1938.svg"] },
    **{ k: "Philippines"                for k in ["Philippines", "Commonwealth of the Philippines", "Philippine Commonwealth", "Second Philippine Republic"] },
    **{ k: "Poland"                     for k in ["Second Polish Republic", "Polish government-in-exile", "Poland"] },
    **{ k: "Romania"                    for k in ["Kingdom of Romania", "Kingdom of Romania, (!) Nazi Germany"] },
    **{ k: "Slovakia"                   for k in ["Slovak Republic (1939-1945)"] },
    **{ k: "South Africa"               for k in ["Union of South Africa"] },
    **{ k: "Soviet Union"               for k in ["Soviet Union", "USSR"] },
    **{ k: "Thailand"                   for k in ["Thailand"] },
    **{ k: "United States"              for k in ["United States", "USA", "United States of America", "US"] },
    **{ k: "Vichy France"               for k in ["Vichy France"] },

    **{ k: "Serbia"       for k in ["Flag of Serbian State Guard.svg"] },

    **{ k: "Yugoslavia"                 for k in ["Chetniks", "Chetniks Flag.svg", "Communist Party of Yugoslavia Flag-cyr (1920–1952).svg", 
                                            "Kingdom of Yugoslavia", "Yugoslav Partisans", "Yugoslav Partisans flag (1942-1945).svg", 
                                            "Flag of the Serbian Partisans.svg", "Flag of the Slovene Partisans.svg",
                                            "Democratic Federal Yugoslavia", "Flag of Yugoslavia (1943–1946).svg",
                                            ] },

    **{ k: "Slovenia"                    for k in ["Flag of the Slovene Home Guard.svg"] },
    **{ k: "Montenegro"                  for k in ["Flag of the Principality of Montenegro.svg"] },
    **{ k: "Manchukuo"                    for k in ["Manchukuo"] },
    **{ k: "Mengjiang"                    for k in ["Mengjiang"] },


    **{ k: "Islam"                      for k in ["islam creciente.png"] },
}







COUNTRY_TO_COLOR = {
    "Default":                  "#7C7C7C",
    "Other":                    "#7C7C7C",

    "Albania":                  "#503F31",
    "Australia":                "#e76937",
    "Belgium":                  "#e4c620",
    "Brazil":                   "#037948",
    "Britain":                  "#ff0a0a",
    "British India":            "#883c3c",
    "Bulgaria":                 "#375a40",
    "Canada":                   "#e41d4f",
    "China":                    "#dbc85a",
    "Croatia":                  "#542d86",
    "Czechoslovakia":           "#394975",
    "Danzig":                   "#3b2a2a",
    "Denmark":                  "#974944",
    "Empire of Japan":          "#eecfec",
    "Finland":                  "#aef1e1",
    "France":                   "#3564ff",
    "Germany":                  "#363636",
    "Greece":                   "#7cc2d8",
    "Hungary":                  "#607745",
    "Iceland":                  "#b6cdd1",
    "Italy":                    "#315730",
    "Italian Partisans":        "#a2cf6e",
    "Iran":                     "#099204",
    "Iraq":                     "#565c00",
    "Luxembourg":               "#0b6092",
    "Malayan Union":            "#7A7DAD",
    "Manchukuo":                "#c08a58",
    "Mengjiang":                "#daac82",
    "Montenegro":               "#b38aff",
    "Netherlands":              "#a38e48",
    "New Zealand":              "#7a2432",
    "Norway":                   "#4E3C3C",
    "Palestine":                "#b47500",
    "Philippines":              "#31a097",
    "Poland":                   "#ce6c54",
    "Romania":                  "#69580a",
    "South Africa":             "#be3c00",
    "Slovakia":                 "#758D8C",
    "Slovenia":                 "#504a74",
    "Soviet Union":             "#640000",
    "Thailand":                 "#a78e6e",
    "United States":            "#5fbce7",
    "Serbia":                   "#529782",
    "Yugoslavia":               "#1d1e4e",
    "Vichy France":             "#26415a",

    "Islam":                    "#000000",
}


NAME_TO_COUNTRY = {
    **{ k: "Other" for k in ["Subhas Chandra Bose"]},

    **{ k: "Albania" for k in ["Džemail Koničanin"]},

    **{ k: "Australia" for k in ["Frederick Galleghan", "Gordon Bennett (general)", "Iven Mackay", "Henty Henty-Creer",
                                 "Jack Stevens (officer)", "John Augustine Collins"
                                 ] },

    **{ k: "Brazil" for k in ["Mascarenhas de Morais"]},

    **{ k: "Britain" for k in ["Alan Cunningham", "Andrew Browne Cunningham", "Arthur Coningham (RAF officer)", 
                               "Reade Godwin-Austen", "Allan Cameron", "Archibald Wavell", "Arthur Harris", "Arthur Percival",
                                "Bernard Montgomery", "Bertram Ramsay", "Brian Horrocks", 
                                "Claude Auchinleck", "Frederic Wake-Walker", "Harold Alexander", 
                                "Henry Maitland Wilson", "Henry Maitland Wilson, 1st Baron Wilson", "Hugh Dowding", 
                                "James Somerville", "John Crocker", "John Durnford-Slater", "John Tovey", "Keith Park", 
                                "Kenneth Anderson (British Army officer)", "Lancelot Holland", "Miles Dempsey", "Neil Ritchie",
                                "Philip Vian", "Ronnie Tod", "Sir John Smyth, 1st Baronet", "William Gott", "William Platt",
                                "William Slim", "David Balme", "Arthur Reginald Chater", "Archibald Beauman", "Charles Clark",
                                "Charles Portal", "Charles Eric Morgan", "Claud Barry", "Colin Frederick Blackden",
                                "Colin Gubbins", "David Stirling", "Deric Holland-Martin", "Donald Cameron (VC)",
                                "Dudley Pound", "AJB Baker-Cresswell", "Evelyn Barker", "Willoughby Norrie",
                                "Geoffrey Appleyard", "George Erskine", "Gerard Muirhead-Gould", "Godfrey Place",
                                "Guy D'Oyly-Hughes", "Guy Gibson", "H. E. Horan", "Harold Franklyn", "Herbert Hasler",
                                "J. S. M. Richardson", "James Pelly-Fry", "James Rivett-Carnac (Royal Navy officer)",
                                "James Somerville (admiral)", "John Charles Campbell", "John Frost (British Army officer)",
                                "John Godwin RNVR", "Lewis Lyne", "Lionel Frederick Robert Kenyon",
                                "Lumley Lyster", "Major Ronnie Tod", "Merton Beckwith-Smith", "Michael O'Moore Creagh",
                                "Noel Beresford-Peirse", "P. C. W. Manwaring", "Philip Mack", "Philip Neame",
                                "Ranald Reid", "Reginald Portal", "Richard O'Connor", "Robert Hesketh Bevan",
                                "Simon Christopher Joseph Fraser, 17th Lord Lovat", "Sq. Ldr. John D. Nettleton",
                                "Thomas Hutton", "Tony Pugsley", "Victor Fortune", "Walter Clutterbuck",
                                "William Fox-Pitt (British Army)", "William Fraser (British Army officer)",
                                "William Gladstone Agnew", "William Hinde (soldier)"
                                ]},

    **{ k: "British India" for k in ["Lewis Heath", "Geoffry Scoones", "Reginald Savory"]},

    **{ k: "Canada" for k in ["Harold Taylor Wood Grant"]},

    **{ k: "Croatia" for k in ["Marko Vrkljan", "Slavko Kvaternik", "Vladimir Laxa"]},

    **{ k: "Empire of Japan" for k in ["Akinosuke Oka", "Aritomo Gotō", "Chūichi Nagumo", "Gunichi Mikawa", "Harukichi Hyakutake", 
                                       "Hiroaki Abe", "Isoroku Yamamoto", "Japanese Eighteenth Army", "Jinichi Kusaka", 
                                       "Kakuji Kakuta", "Kiyotake Kawaguchi", "Nobutake Kondō", "Raizō Tanaka", 
                                       "Renya Mutaguchi", "Rikichi Tsukada", "Shigeyoshi Inoue", "Shintarō Hashimoto", 
                                       "Takuma Nishimura", "Takuro Matsui", "Tamon Yamaguchi", "Tomitaro Horii", 
                                       "Tomoyuki Yamashita", "Toshinari Shōji", "Eiji Gotō", "Goichi Oie",
                                       "Hankyu Sasaki", "Hatsuo Tsukamoto", "Hideyoshi Obata", "Keiji Shibazaki",
                                       "Kiyochi Ogata", "Kunio Nakagawa", "Takeyoshi Inagaki", "Masakasu Kawabe",
                                       "Masakazu Ogaki", "Masami Kobayashi", "Masao Maruyama (Japanese Army officer)",
                                       "Mitsuo Fuchida", "Monzo Akiyama", "Mukaide", "Murai Kenjiro", "Nariyoshi Tsunehiro",
                                       "Nomasu Nakaguma", "Prince Naruhiko Higashikuni", "Rinosuke Ichimaru",
                                       "Sadae Inoue", "Sadamichi Kajioka", "Saisuke Fujino", 'Seigō Yamagata',
                                       "Shiegeo Gotanda", "Shigematsu Sakaibara", "Susumu Morioka", "Tadashi Sumiyoshi",
                                       "Takatsugu Jōjima", "Takeshi Takashina", "Tetsuo Ogawa", "Ushio Goto",
                                       "Yamada Michiyuki", "Yoshimi Nishida", "Yumio Nasu"
                                       ]},
    **{ k: "Finland" for k in ["Antero Svensson", "Paavo Talvela", "Woldemar Hägglund", "Erkki Raappana",
                               "Kustaa Tapola", "Lauri Tiainen", "Lieutenant Fred Luther", "Per Ole Ekholm"
                               ]},

    **{ k: "France" for k in ["Alphonse Juin", "Charles de Gaulle", "Maxime Weygand", "Dimitri Amilakhvari",
                                "François Darlan", "Gustave Mesny", "Jean-Baptiste Molinié", "Marcel-Bruno Gensoul",
                                "Marie-Pierre Kœnig", "Pierre Louis Félix Lanquetot", "Ralph Monclar",
                                "Joseph de Monsabert"]},

    **{ k: "Greece" for k in ["Alexandros Papagos", "Georgios Blessas", "Lt. Col. Vasilios Mantzouranis (80th Reg.)",
                              ]},
    **{ k: "Germany" for k in ["Albert Kesselring", "Alfred Wäger", "Alwin Wolz", "Eberhard von Mackensen", 
                               "Eccard Freiherr von Gablenz", "Erich Brandenberger", "Erich von Manstein", 
                               "Erwin Rommel", "Franz Kohlauf", "Friedrich-Wilhelm Müller", "Gerd von Rundstedt", 
                               "Gerhard Wilck", "Gustav-Adolf von Zangen", "Günther von Kluge", "Hans Karl Meyer", 
                               "Heinz Guderian", "Hermann Göring", "Hugo Sperrle", "Joachim Lemelsen", "Johannes Blaskowitz", 
                               "Josef Dietrich", "Kurt Feldt", "Kurt Student", "Ludwig Crüwell", "Nikolaus von Falkenhorst", 
                               "Otto Ciliax", "Rudolf Veiel", "Sepp Dietrich", "Traugott Herr", "Valentin Feurstein", 
                               "Viktor von Schwedler", "Walter Model", "Walter Nehring", "Wilhelm List", "Wolfram Freiherr von Richthofen", 
                               "Kurt Feldt", "Erich Etienne", "Erich Höpner", "Erich Raeder", "Ernst-Felix Krüder", "Felix Steiner",
                               "Ludwig Crüwell", "Walter Neumann", "Fritz Bayerlein", "Fritz Kühne", "Gustav von Vaerst",
                               "Hans Erdmenger", "Hans von Obstfelder", "Heinrich Eberbach", "Heinz von Westernhagen",
                               "Herbert Schmidt (Fallschirmjäger)", "Kurt Feldt", "Josef Kammhuber", "Joseph Schmid",
                               "Julius Bachmann", "Karl Dönitz", "Kuno-Hans von Both", "Werner Ostendorff",
                               "Lieutenant General Ludwig von Leyen", "Ludwig Ritter von Radlmeier", "Matthias Kleinheisterkamp",
                               "Max von Hartlieb-Walsporn", "Michael Wittmann", "Oberst Groschke", "Oskar Blümm", "Oskar Kummetz",
                               "Otto Kähler", "Rolf Carls", "Stefan de Walden", "Theodor Busse", "Walter Neumann-Silkow",
                               "Walther Wenck", "Wilhelm Marschall", "Eugen von Schobert"
                               ]},

    **{ k: "Italy" for k in ["Adriano M. D. Adimari", "Alfredo Bonezzi", "Prince Amedeo, Duke of Aosta", "Angelo Iachino",
                             "Annibale Bergonzoli", "Carlo De Simone", "Enea Navarini", "Ettore Baldassarre", "Ettore Bastico", "Gastone Gambara", 
                             "Giovanni Messe", "Giuseppe De Stefanis", "Guglielmo Nasi", "Inigo Campioni", 
                             "Italo Gariboldi", "Mario Balotta", "Mario Roatta", "Rodolfo Graziani", "Ugo Cavallero", "Augusto Ugolini", "Arturo Bertello",
                             "Antonino Toscano", "Bruno Brivonesi", "Costantino Borsini", "Enrico Baroni", "Enrico Pitassi Mannella",
                             "Federico Ferrari Orsi", "Felice Leggio", "Ferdinando Casardi", "Ferdinando Tanucci", 
                             "Giacomo Carboni", "Gino Pavesi", "Giuseppe Tellera", "Luigi Faggioni", "Marino Fasan",
                             "Mario Berti", "Maximilian von Herff", "Nicolangelo Carnimeo", "Orlando Lorenzini", "Paolo Aloisi",
                             "Pietro Maletti", "Pietro de Cristofaro", "Saverio Marotta", "Ugo Montemurro", "Valentino Babini",
                             "Junio Valerio Borghese"
                             ]},

    **{ k: "Italian Partisans" for k in ["Alberto Agresti", "Amedeo Manzo", "Antonio Tarsia in Curia", "Giovanni Abbate",
                    "Ermete Bonomi", "Carmine Musella", "Carlo Bianco", "Aurelio Spoto", "Stefano Fadda", "Francesco Cibarelli",
                    "Amedeo Manzo", "Francesco Bilardo", "Gennaro Zengo", "Francesco Amicarelli", "Mario Orbitello", "Salvatore Amato",
                    "Raffaele Viglione", "Tito Murolo"]},

    **{ k: "Netherlands" for k in ["P. W. Scharroo", "Christiaan Boers", "Hoyte Jolles", 
                                   ]},
    **{ k: "New Zealand" for k in ["Bernard Freyberg", "Willoughby Norrie, 1st Baron Norrie"]},
    **{ k: "Norway" for k in ["Arne Sunde", "Ernst Gustav Adolf Ullring", "Ivar Navelsaker", "Kristian Løken",
                              "Leif Welding-Olsen", "Nils Christoffer Bøckman"
                              ]},
    **{ k: "" for k in []},
    **{ k: "" for k in []},
    **{ k: "" for k in []},
    **{ k: "" for k in []},
    **{ k: "Philippines" for k in ["Simeon De Jesus"]},
    **{ k: "Poland" for k in ["Bronislaw Duch", "Colonel Jan Karcz", "Dawid Wdowiński", "Janusz Gąsiorowski", "Józef Cwynar",
                              "Leon Rodal", "Lieutenant Władysław Kossakowski", "Lucjan Stanek", "Marek Edelman", "Maurycy Orzech",
                              "Mordechai Anielewicz", "Paweł Frenkiel", "Stanisław Wyderko", "Stefan Kwiatkowski",
                              "Viktor Lomidze", "Witold Radziulewicz", "Yitzhak Zuckerman", "Zivia Lubetkin", "Karol Świerczewski"
                              ]},



    **{ k: "Soviet Union" for k in ["Aleksei Nikolayevich Krutikov", "Aleksei Vinogradov", "Andrei Yeremenko", "Filipp Gorelenko", 
                                    "Georgy Zhukov", "Ivan Konev", "Ivan Tyulenev", "Kirill Meretskov", "Vasily Sokolovsky", 
                                    "Dmitri Danilovich Lelyushenko", "Dimitri Kozlov", "Grigori Shtern", "Ivan Khabarov",
                                    "M.S. Yevstigneyev", "Peter Alexandrov", "Valerian Frolov", "Vasily Vorontsov (General)"
                                    ]},
    **{ k: "United States" for k in ["Albert M. Jones", "Alexander Vandegrift", "Andrew Davis Bruce",
                                     "Allen H. Turnage", "Amor L. Sims", "Andrew Anderson", "Carl Spaatz", 
                                     "Clifton B. Cates", "Courtney Hodges", "George M. Jones", "Holland Smith", 
                                     "Jimmy Doolittle", "John P. Lucas", "Mark W. Clark", "Merritt A. Edson", 
                                     "Omar Bradley", "Richmond K. Turner", "Roy Geiger", "William H. Rupertus", "Charles D. Johnston",
                                     "Charles H. Corlett", "Chesty Puller", "Daniel J. Callaghan", "Dwight Eisenhower",
                                     "Edward M. Postlethwait", "Evans Carlson", "George J. McMillin", "George M. Parker",
                                     "George Price Hays", "Graham Stokes", "Harold D. Harris", "Harry Schmidt (USMC)", "Harry W. Hill (admiral)",
                                     "Henry G. Leonard, Jr", "Henry T. Elrod", "Herman H. Hanneken", "J. A. Blackburn",
                                     "James Devereux", "John T. Walker (USMC)", "Lemuel C. Shepherd Jr.",
                                     "Leroy D. Brummitt", "Leroy E. Nelson", "William C. Wright", "M. Keely", "Norman Scott (admiral)",
                                     "Paul J. Mueller", "Paul A. Putnam", "Ralph C. Smith", "Richard L. Conolly", "Robert C. Giffen",
                                     "Samuel B. Griffith", "Thomas E. Watson (USMC)", 'William Halsey Jr.', "William Hood Simpson",
                                     "William Orlando Darby", "William Rupertus", "William T. Owen", "Willis Augustus Lee",
                                     "Winfield S. Cunningham"
                                     ]},

                                     
    **{ k: "Vichy France" for k in ["André Marquis", "Henri Dentz", "Jean de Laborde", "Paul Balley", "Marcel Têtu"]},
    **{ k: "Yugoslavia" for k in ["Boško Todorović", "Žarko Mitrović", "Radivoje Kosorić", "Slaviša Vajner Čiča", "Slobodan Princip Seljo",
                                  "Slobodan Princip"]},
}