NORMALIZE_COUNTRY_NAME = {
    **{ k: "Arabia"                     for k in ["Arab Revolt"] },
    **{ k: "Armenia"                    for k in ["First Republic of Armenia", "flag of armenia (1918–1922).svg"] },
    **{ k: "Assyria"                    for k in ["Assyria", "flag of the assyrian volunteers.svg", "Flag of the Assyrian Volunteers.svg"] },
    **{ k: "Australia"                  for k in ["Australia"] },
    **{ k: "Austria-Hungary"            for k in ["Austria-Hungary", "Habsburg Monarchy", "Austria-Hungary-flag-1869-1914-naval-1786-1869-merchant.svg"] },
    **{ k: "Azerbaijan"                 for k in ["Azerbaijan Democratic Republic"] },
    **{ k: "Belgian Congo"              for k in ["Belgian Congo"] },
    **{ k: "Belgium"                    for k in ["Belgium"] },
    **{ k: "Bohemia"                    for k in ["Bohemia", "Kingdom of Bohemia"] }, # TODO who?
    **{ k: "Brazil"                     for k in ["First Brazilian Republic"] },
    **{ k: "British Empire"             for k in ["British Empire", "Great Britain", "Newfoundland", "UK", "UKGBI", "United Kingdom", "United Kingdom of Great Britain and Ireland"] }, # TODO?
    **{ k: "British India"              for k in ["British India", "British Raj"] },
    **{ k: "Bulgaria"                   for k in ["Bulgaria", "Kingdom of Bulgaria", "Tsardom of Bulgaria (1908–1946)"] },
    **{ k: "Canada"                     for k in ["Canada"] },
    **{ k: "Egypt"                      for k in ["Sultanate of Egypt"] },
    **{ k: "Estonia"                    for k in ["Estonia"] },
    **{ k: "Finland"                    for k in ["Finland", "Flag of Finland 1918 (state).svg"] },
    **{ k: "France"                     for k in ["FRA-3", "France", "French Third Republic", "Kingdom of the French"] }, # TODO for sure?
    **{ k: "German Colonies"            for k in ["German South West Africa", "German New Guinea", "German Samoa", "Reichskolonialflagge.svg"] },
    **{ k: "Germany"                    for k in ["German Empire", "Kingdom of Bavaria", "Kingdom of Prussia", "Kingdom of Württemberg", "Prussia",
                                                  "Flag of Germany (1867–1918).svg"] },
    **{ k: "Greece"                     for k in ["Greece", "Kingdom of Greece"] },
    **{ k: "Italy"                      for k in ["Kingdom of Italy"] },
    **{ k: "Japan"                      for k in ["Empire of Japan"] },
    **{ k: "Kurdistan"                  for k in ["Kurdistan"] },
    **{ k: "Lahej"                      for k in ["Lahej"] }, # TODO who
    **{ k: "Liberia"                    for k in ["Flag of Liberia.svg"] },
    **{ k: "Montenegro"                 for k in ["Kingdom of Montenegro"] },
    **{ k: "New Zealand"                for k in ["Dominion of New Zealand", "New Zealand"] },
    **{ k: "Ottoman Empire"             for k in ["Ottoman Empire", "Flag of the Ottoman Empire (1844–1922).svg"] },
    **{ k: "Persia"                     for k in ["Iran", "Persia", "Early 20th Century Qajar Flag.svg"] },
    **{ k: "Poland"                     for k in ["Poland", "POL"] },
    **{ k: "Portugal"                   for k in ["First Portuguese Republic", "Portugal"] },
    **{ k: "Romania"                    for k in ["Kingdom of Romania", "Romania"] },
    **{ k: "Russia"                     for k in ["Russia", "Russian Empire", "Russian Republic", "Flag_of_Russia (1914-1917).svg", "Flag_of_Russia_(1914-1917).svg"] },
    **{ k: "Serbia"                     for k in ["Kingdom of Serbia"] },
    **{ k: "South Africa"               for k in ["South Africa", "Union of South Africa", "ZAR", "Red Ensign of South Africa (1912–1951).svg"] },
    **{ k: "Soviets"                    for k in ["Russian SFSR", "Russian Soviet Republic", "Soviet Russia", "Baku Commune.svg", "Red flag.svg"] },
    **{ k: "Sweden"                     for k in ["Sweden", "Flag of the Swedish Brigade (Ruotsalainen prikaati).svg"] },
    **{ k: "Transcaucasian Republic"    for k in ["Transcaucasian Democratic Federative Republic"] },
    **{ k: "Ukraine"                    for k in ["прапор україни з великим гербом унр.png"] },
    **{ k: "United States"              for k in ["US", "USA", "United States", "United States Navy", "United States of America", 
                                                  "naval jack of the united states (1912–1959).svg", "us naval jack 48 stars.svg"] },

    **{ k: "Other"                      for k in ["Flag of the Centrocaspian Dictatorship.svg"] },
    **{ k: "socialists"                 for k in ["socialist red flag.svg", "Socialist red flag.svg"] }, # TODO who???
}



NAME_TO_COUNTRY = { # TODO check if there are no russians/germans in the finnish whites/reds (?)
    **{ k: "Finnish Reds"               for k in ["A. Backman", "Adam Krogerus", "Adolf Aminoff", "Arvid Leinonen",
                                                  "Heikki Kaljunen", "M. V. Prigorovski", "Matti Autio",
                                                  "Oskar Rantala", "Emil Parkkinen", "Kaarlo Lähteenmäki",
                                                  "Erkki Karjalainen", "Mikko Kokko", "Edvard Gylling", "Kullervo Manner",
                                                  "Mikhail Svechnikov", "Eino Siukola", "Leander Viljanen",
                                                  "Vihtori Hurri", "Emil Koski", "Herman Järvinen",
                                                  "Oskar Johansson"] },
    **{ k: "Finnish Whites"             for k in ["Aarne Sihvo", "Ernst Löfström", "Lennart Oesch", "C. W. Malm",
                                                  "Johan Sainio", "Carl Nordensvan", "Martin Ekström", "Martin Wetzer",
                                                  "Eduard Ausfeld (colonel)", "K. F. Wilkman", "Ulrich von Coler",
                                                  "Oskar Wilkman", "Torsten Aminoff", "Paul Wallenius"] },

    **{ k: "Ethiopian Zewditu loyalists"        for k in ["Fitawrari Habte Giyorgis Ras Kebede Mengesha"] },
    **{ k: "Ethiopian Lij Iyasu loyalists"      for k in ["Negus Mikael of Wollo"] },

    **{ k: "Arabia"                     for k in ["Muhammad ‘Ali al-Qazwini"] },
    **{ k: "Armenia"                    for k in ["Aram Manukian", "Christophor Araratov", "Daniel Bek-Pirumyan",
                                                  "Movses Silikyan", "Poghos Bek-Pirumyan", "Armenak Yekarian",
                                                  "Ishkhan (fedayi)", "Kâzım Özalp", "Drastamat Kanayan", "Jangir Agha",
                                                  "Garegin Nzhdeh"] },
    **{ k: "Assyria"                    for k in [] },
    **{ k: "Australia"                  for k in ["Edward Fowell Martin"] },
    **{ k: "Austria-Hungary"            for k in [] },
    **{ k: "Azerbaijan"                 for k in [] },
    **{ k: "Belgian Congo"              for k in [] },
    **{ k: "Belgium"                    for k in ["Augustin Michel", "Jules Jacques de Dixmude", "Louis Ruquoy"] },
    **{ k: "Bohemia"                    for k in [] },
    **{ k: "Brazil"                     for k in [] },
    **{ k: "British Empire"             for k in ["A. E. Berry", "A. F. Redfern", "H. S. Collins", 
                                                  "Frederick Bryant", "A. W. Abercrombie", "A. Wilmot-Smith",
                                                  "Henry G. L. Oliphant", "Horace Hood", "Godfrey Herbert", "Colonel Taylor",
                                                  "Edward Evans, 1st Baron Mountevans", "Frederick Campbell",
                                                  "G. F. Gorringe", "General Sheppard", "H. B. Potter",
                                                  "Hew Dalrymple Fanshawe", "Ivor Maxse", "J. R. C. Cavendish",
                                                  "Vincent Molteno", "James Willcocks", "John Drummond",
                                                  "Robert Johnson", "Wilmot Nicholson", "John Du Cane",
                                                  "Reginald Bacon"] },
    **{ k: "British India"              for k in ["Charles Melliss", "Henry D'Urban Keary", "William Peyton"] },
    **{ k: "Bulgaria"                   for k in [] },
    **{ k: "Canada"                     for k in ["Edwin Alderson"] },
    **{ k: "Egypt"                      for k in ["Reginald Wingate", ] },
    **{ k: "Estonia"                    for k in [] },
    **{ k: "Finland"                    for k in [] },
    **{ k: "France"                     for k in ["R. Castaing", "Pierre Ronarc'h", "Colonel Ruef", "Frédéric-Georges Herr",
                                                  "Louis de Maud'huy", "Joseph Anthelme Fournier", "Henry Victor Deligny",
                                                  "Louis Conneau", "Lucjan Malcz", "Osmont d'Amilly", "Václav Dostal",
                                                  "Noel de Castelnau"] },
    **{ k: "German Colonies"            for k in ["Captain von Lieberman", "Eduard Haber", "Hans Von Kruggenmeyer",
                                                  "Georg Pfähler"] },
    **{ k: "Germany"                    for k in ["Andreas Michelsen", "Bernd Wegener", "Klaus Hansen", "Oskar Heinecke",
                                                  "Oskar Heinecke", "Friedrich-Wilhelm von Chappuis", "Major Rothe",
                                                  "Theophil Gautier", "Hugo von Wasielewski", "Ewald von Lochow",
                                                  "Konstantin Schmidt von Knobelsdorf", "Friedrich Boedicker",
                                                  "Hans Gaede", "Hans von Zwehl", "Hauptmann von Calm (Le Quesnoy garrison)",
                                                  "Paul Heinrich", "Otto Weddigen", "Ludwig von Schröder",
                                                  "Rudolf Schneider (captain)"] },
    **{ k: "Greece"                     for k in [] },
    **{ k: "Italy"                      for k in [] },
    **{ k: "Japan"                      for k in [] },
    **{ k: "Kurdistan"                  for k in [] },
    **{ k: "Lahej"                      for k in [] },
    **{ k: "Liberia"                    for k in [] },
    **{ k: "Montenegro"                 for k in [] },
    **{ k: "New Zealand"                for k in [] },
    **{ k: "Ottoman Empire"             for k in ["Ahmed Izzet Pasha", "Zekeriya Zihni Bey", "Nurettin Özsü",
                                                  "Djevdet Bey", "Esad Pasa", "Kezim Pasa", "Jaafar Pasha"] },
    **{ k: "Persia"                     for k in [] },
    **{ k: "Poland"                     for k in ["Bolesław Jaźwiński", "Józef Dowbor-Muśnicki", "Stanisław Wrzaliński",
                                                  "Władysław Anders"] },
    **{ k: "Portugal"                   for k in [] },
    **{ k: "Romania"                    for k in ["Alexandru Cӑlinescu"] },
    **{ k: "Russia"                     for k in ["Nikolai Pavlovich Bobyr", "Pavel Shishko"] },
    **{ k: "Serbia"                     for k in [] },
    **{ k: "South Africa"               for k in ["Coen Brits", "Henry Lukin", "Percival Scott Beves"] },
    **{ k: "Soviets"                    for k in ["Jukums Vācietis", "gen. Maksymowicz", "gen. Romanowskij"] },
    **{ k: "Sweden"                     for k in [] },
    **{ k: "Transcaucasian Republic"    for k in [] },
    **{ k: "Ukraine"                    for k in [] },
    **{ k: "United States"              for k in [] },

    **{ k: "Other"                      for k in ["Ali Dinar", # Darfur Sultanate
                                                  "Ramadan Ali (Fur Army)", # Darfur Sultanate
                                                  "Sulayman Ali", # Darfur Sultanate
                                                  "Mandume ya Ndemufayo", # Oukwanyama
                                                  ] },
}

COUNTRY_TO_COLOR = {
    "Default":                  "#7C7C7C",

    "Arabia":                   "#03500e",
    "Armenia":                  "#ff6600",
    "Assyria":                  "#ffff00",
    "Australia":                "#ff4444",
    "Austria-Hungary":          "#bdb09c",
    "Azerbaijan":               "#001eca",
    "Belgian Congo":            "#cac720",
    "Belgium":                  "#e4c620",
    "Bohemia":                  "#9c6c05",
    "Brazil":                   "#037948",
    "British Empire":           "#ff0a0a",
    "British India":            "#ff4444",
    "Bulgaria":                 "#375a40",
    "Canada":                   "#ff4444",
    "Egypt":                    "#ff4444",
    "Estonia":                  "#2a57d3",
    "Finland":                  "#aef1e1",
    "France":                   "#3564ff",
    "German Colonies":          "#466169",
    "Germany":                  "#212A3B",
    "Greece":                   "#7cc2d8",
    "Italy":                    "#3fcc3a",
    "Japan":                    "#eecfec",
    "Kurdistan":                "#bf007f",
    "Lahej":                    "#ff7f00",
    "Liberia":                  "#00ff7f",
    "Montenegro":               "#7f7fff",
    "New Zealand":              "#ff4444",
    "Ottoman Empire":           "#b4dba1",
    "Persia":                   "#099204",
    "Poland":                   "#ce6c54",
    "Portugal":                 "#007C7C",
    "Romania":                  "#d1ab00",
    "Russia":                   "#244126",
    "Serbia":                   "#1b1f53",
    "South Africa":             "#ff4444",
    "Soviets":                  "#640000",
    "Sweden":                   "#051938",
    "Transcaucasian Republic":  "#8332a8",
    "Ukraine":                  "#f1d73e",
    "United States":            "#5fbce7"
}